### ISSUE TITLE
“    raise AttributeError("'{}' object has no attribute '{}'".format( AttributeError: 'DistributedDataParallel' object has no attribute 'model'”

### ISSUE THREAD

**Issue by rockywind** [Megvii-BaseDetection/BEVDepth#12]
Hi，
Great work!

The script is that!
``'
python exps/bev_depth_lss_r50_256x704_128x128_24e.py -b 2 --gpus 2
``

I met the error below that!

``‘
Missing logger folder: outputs/bev_depth_lss_r50_256x704_128x128_24e/lightning_logs
Missing logger folder: outputs/bev_depth_lss_r50_256x704_128x128_24e/lightning_logs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
Traceback (most recent call last):
  File "exps/bev_depth_lss_r50_256x704_128x128_24e.py", line 489, in <module>
    run_cli()
  File "exps/bev_depth_lss_r50_256x704_128x128_24e.py", line 485, in run_cli
    main(args)
  File "exps/bev_depth_lss_r50_256x704_128x128_24e.py", line 454, in main
    trainer.fit(model)
  File "/home/nio/anaconda3/envs/surrounddepth/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/home/nio/anaconda3/envs/surrounddepth/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/home/nio/anaconda3/envs/surrounddepth/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/home/nio/anaconda3/envs/surrounddepth/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/nio/anaconda3/envs/surrounddepth/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1221, in _run
    self._call_callback_hooks("on_fit_start")
  File "/home/nio/anaconda3/envs/surrounddepth/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1636, in _call_callback_hooks
    fn(self, self.lightning_module, *args, **kwargs)
  File "/DATA/xiaoquan.wang/BEVDepth/callbacks/ema.py", line 77, in on_fit_start
    for model_ref in trainer.model.model.modules():
  File "/home/nio/anaconda3/envs/surrounddepth/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DistributedDataParallel' object has no attribute 'model'
Traceback (most recent call last):
  File "/DATA/xiaoquan.wang/BEVDepth/exps/bev_depth_lss_r50_256x704_128x128_24e.py", line 489, in <module>
    run_cli()
  File "/DATA/xiaoquan.wang/BEVDepth/exps/bev_depth_lss_r50_256x704_128x128_24e.py", line 485, in run_cli
    main(args)
  File "/DATA/xiaoquan.wang/BEVDepth/exps/bev_depth_lss_r50_256x704_128x128_24e.py", line 454, in main
    trainer.fit(model)
  File "/home/nio/anaconda3/envs/surrounddepth/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/home/nio/anaconda3/envs/surrounddepth/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/nio/anaconda3/envs/surrounddepth/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/nio/anaconda3/envs/surrounddepth/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1221, in _run
    self._call_callback_hooks("on_fit_start")
  File "/home/nio/anaconda3/envs/surrounddepth/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1636, in _call_callback_hooks
    fn(self, self.lightning_module, *args, **kwargs)
  File "/DATA/xiaoquan.wang/BEVDepth/callbacks/ema.py", line 77, in on_fit_start
    for model_ref in trainer.model.model.modules():
  File "/home/nio/anaconda3/envs/surrounddepth/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DistributedDataParallel' object has no attribute 'model'
``‘

**Comment by yinchimaoliang** [comment]
Can you provide more details like the version of python, pytorch and pytorch-lightning?
