### ISSUE TITLE
AttributeError: 'LightningDistributedModule' object has no attribute '_parameters'

### ISSUE THREAD

**Issue by Bluffish** [Megvii-BaseDetection/BEVDepth#13]
`python ./exps/bev_depth_lss_r50_256x704_128x128_24e.py --amp_backend native -b 1 --gpus 1`

gives error

`Traceback (most recent call last):
  File "/mnt/data/home/bny220000/projects/bevdepth/./exps/bev_depth_lss_r50_256x704_128x128_24e.py", line 486, in <module>
    run_cli()
  File "/mnt/data/home/bny220000/projects/bevdepth/./exps/bev_depth_lss_r50_256x704_128x128_24e.py", line 482, in run_cli
    main(args)
  File "/mnt/data/home/bny220000/projects/bevdepth/./exps/bev_depth_lss_r50_256x704_128x128_24e.py", line 452, in main
    trainer.fit(model)
  File "/mnt/data/home/bny220000/projects/bevdepth/venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/mnt/data/home/bny220000/projects/bevdepth/venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/mnt/data/home/bny220000/projects/bevdepth/venv/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/mnt/data/home/bny220000/projects/bevdepth/venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/mnt/data/home/bny220000/projects/bevdepth/venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1221, in _run
    self._call_callback_hooks("on_fit_start")
  File "/mnt/data/home/bny220000/projects/bevdepth/venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1636, in _call_callback_hooks
    fn(self, self.lightning_module, *args, **kwargs)
  File "/mnt/data/home/bny220000/projects/bevdepth/callbacks/ema.py", line 83, in on_fit_start
    trainer.ema_model = ModelEMA(trainer.model.cuda(), 0.9990)
  File "/mnt/data/home/bny220000/projects/bevdepth/callbacks/ema.py", line 44, in __init__
    self.ema = deepcopy(
  File "/usr/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.9/copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.9/copy.py", line 272, in _reconstruct
    y.__setstate__(state)
  File "/mnt/data/home/bny220000/projects/bevdepth/venv/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 580, in __setstate__
    parameters, expect_sparse_gradient = self._build_params_for_reducer()
  File "/mnt/data/home/bny220000/projects/bevdepth/venv/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 593, in _build_params_for_reducer
    modules_and_parameters = [
  File "/mnt/data/home/bny220000/projects/bevdepth/venv/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 594, in <listcomp>
    [
  File "/mnt/data/home/bny220000/projects/bevdepth/venv/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 597, in <listcomp>
    for parameter in [
  File "/mnt/data/home/bny220000/projects/bevdepth/venv/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 597, in <listcomp>
    for parameter in [
  File "/mnt/data/home/bny220000/projects/bevdepth/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1470, in named_parameters
    for elem in gen:
  File "/mnt/data/home/bny220000/projects/bevdepth/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1415, in _named_members
    members = get_members_fn(module)
  File "/mnt/data/home/bny220000/projects/bevdepth/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1468, in <lambda>
    lambda module: module._parameters.items(),
  File "/mnt/data/home/bny220000/projects/bevdepth/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LightningDistributedModule' object has no attribute '_parameters'
`

**Comment by yinchimaoliang** [comment]
Can you provide more details like the version of python, pytorch and pytorch-lightning?

**Comment by Bluffish** [comment]
Hello, thanks for the response!

python: 3.9
pytorch: 1.9.0 for cuda 11.1
pytorch-lightning: 1.6.5

**Comment by Joker316701882** [comment]
@Bluffish Hi. Our code works fine on:
python: 3.6.9
pytorch: 1.9.0 for cuda 10.2
pytorch-lightning: 1.5.10.

You could try to downgrade your lightning to our version and try it again.

**Comment by Bluffish** [comment]
This worked, thanks!
