### ISSUE TITLE
When can we have Matrix VT model?

### ISSUE THREAD

**Issue by ClaireTun** [Megvii-BaseDetection/BEVDepth#144]

**Comment by ZRandomize** [comment]
The model is already (here)[https://github.com/Megvii-BaseDetection/BEVDepth/blob/main/bevdepth/models/matrixvt_det.py] !

**Comment by ClaireTun** [comment]
> The model is already [here](https://github.com/Megvii-BaseDetection/BEVDepth/blob/main/bevdepth/models/matrixvt_det.py) !

Well ,I mean the checkpoints

**Comment by ZRandomize** [comment]
The weights is available [here](https://github.com/ZRandomize/MatrixVT/releases/tag/weights)~

**Comment by wansdd** [comment]
> The weights is available [here](https://github.com/ZRandomize/MatrixVT/releases/tag/weights)~
hello,when I use 
python bevdepth/exps/nuscenes/MatrixVT/matrixvt_bev_depth_lss_r50_256x704_128x128_24e_ema.py  --ckpt_path /Programs/BEVDepth/matrixvt_det_r50_cbgs.pth  -e  -p -b 2 --gpus 1
this command ,an error meets
Restoring states from the checkpoint path at /Programs/BEVDepth/matrixvt_det_r50_cbgs.pth
Traceback (most recent call last):
  File "bevdepth/exps/nuscenes/MatrixVT/matrixvt_bev_depth_lss_r50_256x704_128x128_24e_ema.py", line 22, in <module>
    run_cli(
  File "/Programs/BEVDepth/bevdepth/exps/base_cli.py", line 73, in run_cli
    trainer.test(model, ckpt_path=args.ckpt_path)
  File "/opt/miniconda/envs/BEVDepth/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 939, in test
    return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)
  File "/opt/miniconda/envs/BEVDepth/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 722, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/opt/miniconda/envs/BEVDepth/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/opt/miniconda/envs/BEVDepth/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 986, in _test_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/miniconda/envs/BEVDepth/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1180, in _run
    self._restore_modules_and_callbacks(ckpt_path)
  File "/opt/miniconda/envs/BEVDepth/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1142, in _restore_modules_and_callbacks
    self._checkpoint_connector.restore_model()
  File "/opt/miniconda/envs/BEVDepth/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 179, in restore_model
    self.trainer.strategy.load_model_state_dict(self._loaded_checkpoint)
  File "/opt/miniconda/envs/BEVDepth/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 320, in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"])
KeyError: 'state_dict'
How can I deal with this problem?
