### ISSUE TITLE
AssertionError: Error: Only <= 500 boxes per sample allowed! during evaluation

### ISSUE THREAD

**Issue by Bluffish** [Megvii-BaseDetection/BEVDepth#26]
Hello, upon training a new model and running evaluation using the nuscenes trainval, I run in to this error: 

`Traceback (most recent call last):
  File "./exps/bev_depth_lss_r50_256x704_128x128_20e_cbgs_2key_da.py", line 156, in <module>
    run_cli()
  File "./exps/bev_depth_lss_r50_256x704_128x128_20e_cbgs_2key_da.py", line 152, in run_cli
    main(args)
  File "./exps/bev_depth_lss_r50_256x704_128x128_20e_cbgs_2key_da.py", line 120, in main
    trainer.test(model, ckpt_path=args.ckpt_path)
  File "/data/bny220000/projects/bevdepth/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 911, in test
    return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)
  File "/data/bny220000/projects/bevdepth/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 698, in _call_and_handle_interrupt
    self.training_type_plugin.reconciliate_processes(traceback.format_exc())
  File "/data/bny220000/projects/bevdepth/venv/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 533, in reconciliate_processes
    raise DeadlockDetectedException(f"DeadLock detected from rank: {self.global_rank} \n {trace}")
pytorch_lightning.utilities.exceptions.DeadlockDetectedException: DeadLock detected from rank: 0
 Traceback (most recent call last):
  File "/data/bny220000/projects/bevdepth/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/data/bny220000/projects/bevdepth/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 954, in _test_impl
    results = self._run(model, ckpt_path=self.tested_ckpt_path)
  File "/data/bny220000/projects/bevdepth/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/data/bny220000/projects/bevdepth/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1275, in _dispatch
    self.training_type_plugin.start_evaluating(self)
  File "/data/bny220000/projects/bevdepth/venv/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 207, in start_evaluating
    self._results = trainer.run_stage()
  File "/data/bny220000/projects/bevdepth/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1286, in run_stage
    return self._run_evaluate()
  File "/data/bny220000/projects/bevdepth/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1334, in _run_evaluate
    eval_loop_results = self._evaluation_loop.run()
  File "/data/bny220000/projects/bevdepth/venv/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 151, in run
    output = self.on_run_end()
  File "/data/bny220000/projects/bevdepth/venv/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 131, in on_run_end
    self._evaluation_epoch_end(outputs)
  File "/data/bny220000/projects/bevdepth/venv/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 231, in _evaluation_epoch_end
    model.test_epoch_end(outputs)
  File "/data/bny220000/projects/bevdepth/exps/bev_depth_lss_r50_256x704_128x128_24e.py", line 367, in test_epoch_end
    self.evaluator.evaluate(all_pred_results, all_img_metas)
  File "/data/bny220000/projects/bevdepth/evaluators/det_mv_evaluators.py", line 212, in evaluate
    self._evaluate_single(result_files[name])
  File "/data/bny220000/projects/bevdepth/evaluators/det_mv_evaluators.py", line 90, in _evaluate_single
    nusc_eval = NuScenesEval(nusc,
  File "/data/bny220000/projects/bevdepth/venv/lib/python3.8/site-packages/nuscenes/eval/detection/evaluate.py", line 80, in __init__
    self.pred_boxes, self.meta = load_prediction(self.result_path, self.cfg.max_boxes_per_sample, DetectionBox,
  File "/data/bny220000/projects/bevdepth/venv/lib/python3.8/site-packages/nuscenes/eval/common/loaders.py", line 47, in load_prediction
    assert len(all_results.boxes[sample_token]) <= max_boxes_per_sample, \
AssertionError: Error: Only <= 500 boxes per sample allowed!`

**Comment by yinchimaoliang** [comment]
Hi, @Bluffish please refer to `https://github.com/Megvii-BaseDetection/BEVDepth/blob/main/exps/bev_depth_lss_r50_256x704_128x128_24e.py#L155`, this may help you.

**Comment by Bluffish** [comment]
Hello, I already have that in my code. Is there anything else that could be causing this?

**Comment by Bluffish** [comment]
Updating the whole project fixed the problem. Thanks!
